### ISSUE TITLE
LNBits support?

### ISSUE THREAD

**Issue by lylepratt** [andrerfneves/lightning-address#37]
Howdy, just curious if LNBits (https://github.com/lnbits/lnbits-legend#lnbits) support is still on the table. The link in the docs seems to be dead.
Thanks!

**Comment by andrerfneves** [comment]
Probably worth asking on the LNBits repo if you haven't yet, I'm not involved with the project myself.

**Comment by andrerfneves** [comment]
My understanding is LNBits has full support for Lightning Addresses now.

**Comment by lylepratt** [comment]
I wasn't aware you can generate and receive to an LNBits wallet via a LNAddress provided by LNBits itself. Anyone have a link to some docs?

**Comment by andrerfneves** [comment]
Honestly I don't use LNBits that often so wouldn't be the best person to give input here. Maybe @fiatjaf can help?

**Comment by fiatjaf** [comment]
The docs are: you must enter the ~~jungle~~ [Telegram group](https://t.me/lnbits) and ask. Or create an issue on the LNbits repository.

LNbits itself doesn't offer addresses because its accounts don't have names, but the last time I looked there was an extension that allowed you to point an external domain to an account, much like https://github.com/nbd-wtf/satdress does too (see https://payaddress.co/, for example). Or maybe I am missing something.
